spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: xxx
      secret-key: xxx
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-bucket
      sms:
        host: https://smsmsgs.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 1
        appcode: xxx
  application:
    name: gulimall-third-party
server:
  port: 30000
